### ISSUE TITLE
Can there be a 1.16.5 forge flagged version?

### ISSUE THREAD

**Issue by razgriz5000** [irtimaled/BoundingBoxOutlineReloaded#136]
would be nice to have a version flagged for 1.16.5.

**Comment by irtimaled** [comment]
Have you tried the Forge 1.16.3 version with Forge 1.16.5? Many folks have found this combination works just fine.

**Comment by razgriz5000** [comment]
it does function.  when searching for mods, it does not show up as compatible because it is flagged for 1.16.3.  specifically i am using gdlauncher and it does not show it when I try to add it through its interface.  this is more of a quality of life change.

**Comment by trogarus** [comment]
Yes, can I second tagging the last 1-16 file to add 1-16-5 flags so this is available to overwolf curseforge (since many modpac devs use overworlf curseforge to pack and upload their modpacks). Should be easy enough to do, just go into recent files and add the tag in file upload settings here on curseforge.

**Comment by trogarus** [comment]
Just go to https://www.curseforge.com/minecraft/mc-mods/bounding-box-outline-reloaded/files/3081524 and hit edit, then update the tag to include 1-16-5 please, in case you weren't aware of this to update file game version tags. :) Thanks.

**Comment by DemonSlayer112** [comment]
I hope this gets done at somepoint, cant add it to my modpack atm.
If i add it manually the way it is now curseforge may not accept the modpack.
Also the only boundary mods i seen for 1.16

**Comment by irtimaled** [comment]
Done
