### ISSUE TITLE
Feature Request: Display useful information for a current/nearby bounding box structure

### ISSUE THREAD

**Issue by rhullah** [irtimaled/BoundingBoxOutlineReloaded#52]
This is a feature request instead of an issue.  Generally it would nice to have additional information shown concerning nearby bounding box structures.  I specifically have [Villages](https://chunkbase.com/mods/village-info) in mind, and would find it extremely helpful if it could list things like the following:

- Village Id
- Center Point
- Villager Population (count/limit)
- Golem Population (count/limit)
- House count
- Breeding status
- Player Reputation

Then thinking of this generally, if information like this would be helpful for other structures, it'd be nice to display that data as well.

**Comment by ariosos** [comment]
Instead of adding a new feature request, I'll add to this one. 
1 - Make the village sphere horizontal lines instead of dots (or at least an option for lines, unless I don't know if one exists already. Sometimes the dark blue dots "disappear" up close - that is, hard to see). 

2 - Add a 64 block radius sphere for the "return to village" zone where the villager AI will always try and pathfind back. This will be good for villager auto-farming placement.

**Comment by irtimaled** [comment]
With villages going away as a concept in 1.14 it's unlikely that I'll invest in adding new features.
